---
driver:
  name: vagrant
  customize:
    nictype1: 'virtio'
    nictype2: 'virtio'
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/precise64

suites:
  - name: chef_server
    run_list:
      - recipe[platform_chefserver::default]
    attributes:
    driver:
      network:
        - [ 'forwarded_port', { guest: 4243, host: 4243 } ]
        - [ 'private_network', { ip: '192.168.24.50' } ]
      synced_folders:
        - ["cookbooks/", "/var/cookbooks"]
