name 'platform_chefserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-platform_chefserver'
long_description 'Installs/Configures chef-platform_chefserver'
version '0.1.0'
