name 'platform_chefserver'
maintainer 'Jakub Błaszczyk'
maintainer_email 'jakub.blaszczyk@sap.com'
license 'all_rights'
description 'Installs/Configures chef-platform_chefserver'
long_description 'Installs/Configures chef-platform_chefserver'
version '0.1.0'
